add compiler flag
If newer compilers gives you errors like this

```
Configuration.h:45:21: error: ISO C++17 does not allow dynamic exception specifications
   45 |         void load() throw (bool);
      |                     ^~~~~
```

you need to add the CXXFLAGS option to Makefile.